function [fitresult, gof] = accumulationFit(t, r)
%CREATEFIT1(T,R)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : t
%      Y Output: r
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 12-Jul-2018 11:16:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( t, r );

% Set up fittype and options.
ft = fittype( 'A*(1-exp(-(t-toff)/tlife))', 'independent', 't', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.792207329559554 0.959492426392903 0.655740699156587];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'r vs. t', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel t
ylabel r
grid on


